title: Vismantas Home
author: VismantasD
email: vismantas@world
description: > # this means to ignore newlines until "baseurl:"
  Simply Awesome

# social links
twitter_username: VismantasD
github_username:  VismantasD

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
